# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20160802_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
